#Basic numpy

1. Play around with numpy -there are many tutorials that you can google it.
2. Comfortable enough with arrays, list,
indexing, access elements, how to reassign values.
3. For loops with arrays.
4. Can create functions( take input parameters, return a value)




In [1]:
import numpy as np

arr = np.array([1,2,3])

print(arr)

arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d)

print('--for loops by rows here---')
for item in arr2d:
  print('item: ',item)

for rows in range(2):
  for columns in range(3):
    print(arr2d[rows,columns])


#Function
def addition(x,y):
  return x+y

print("3+2 is ",addition(3,2))  


[1 2 3]
[[1 2 3]
 [4 5 6]]
--for loops by rows here---
item:  [1 2 3]
item:  [4 5 6]
1
2
3
4
5
6
3+2 is  5


# Transpose, dot product
1. Randomly initialize two vectors **a** and **b** of the same dimension
2. Perform dot product c = **a.b**

#Matrix multiplication
1. Randomly initialize two matrices **A** and **B** of the same (inner) dimension
2. Perform matrix multiplication  **AB** and **BA** (when is this possible?)
3. Does **AB**= **BA**?


In [ ]:
# YOUR CODE HERE
raise NotImplementedError()