#Basic numpy

1. Play around with numpy -there are many tutorials that you can google it.
2. Comfortable enough with arrays, list,
indexing, access elements, how to reassign values.
3. For loops with arrays.
4. Can create functions( take input parameters, return a value)




In [12]:
import numpy as np

arr = np.array([1,2,3])

print(arr)

arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d)

print('--for loops by rows here---')
for item in arr2d:
  print('item: ',item)

for rows in range(2):
  for columns in range(3):
    print(arr2d[rows,columns])


[1 2 3]
[[1 2 3]
 [4 5 6]]
--for loops by rows here---
item:  [1 2 3]
item:  [4 5 6]
1
2
3
4
5
6


# Transpose, dot product, matrix multiplication