#Basic numpy

1. Play around with numpy -there are many tutorials that you can google it.
2. Comfortable enough with arrays, list,
indexing, access elements, how to reassign values.
3. For loops with arrays.
4. Can create functions( take input parameters, return a value)




In [ ]:
import numpy as np

arr = np.array([1,2,3])

print(arr)

arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d)

print('--for loops by rows here---')
for item in arr2d:
  print('item: ',item)

for rows in range(2):
  for columns in range(3):
    print(arr2d[rows,columns])


#Function
def addition(x,y):
  return x+y

print("3+2 is ",addition(3,2))  


[1 2 3]
[[1 2 3]
 [4 5 6]]
--for loops by rows here---
item:  [1 2 3]
item:  [4 5 6]
1
2
3
4
5
6
3+2 is  5


#Summation of array

In [ ]:
arr= np.random.rand(3)
print('array: ',arr,'sum of array: ',arr.sum())

array: 
 [0.80525451 0.68680372 0.02110816] sum of array:  1.5131663897863739


# Transpose, dot product
1. Randomly initialize two vectors **a** and **b** of the same dimension
2. Perform dot product c = **a.b**

#Matrix multiplication
1. Randomly initialize two matrices **A** and **B** of the same (inner) dimension
2. Perform matrix multiplication  **AB** and **BA** (when is this possible?)
3. Does **AB**= **BA**? If not, how do we set so that **AB**= **BA**?


In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

NotImplementedError: ignored

#Random seed

For reproducibility. Pseudo random generators are not actually random, but deterministic in a sense. 

In [ ]:
import random
random.seed(3)
print(random.random())
random.seed(10)
print(random.random())


print("--------")
for i in range(11):
  random.seed(i)
  print(random.random())


#Torch exercise 
-to change the shape of an array in torch/tensor, use view and re assign the variable


In [5]:
import torch
a=torch.rand(4,4)
print(a)

print("\n---Reshaped tensor----\n")
a = a.view(8,2)
print(a)

tensor([[0.4959, 0.8053, 0.9640, 0.0717],
        [0.0647, 0.5012, 0.1353, 0.7119],
        [0.6708, 0.3900, 0.9065, 0.0540],
        [0.1018, 0.0934, 0.9951, 0.4318]])

---Reshaped tensor----

tensor([[0.4959, 0.8053],
        [0.9640, 0.0717],
        [0.0647, 0.5012],
        [0.1353, 0.7119],
        [0.6708, 0.3900],
        [0.9065, 0.0540],
        [0.1018, 0.0934],
        [0.9951, 0.4318]])
